### ISSUE TITLE
Arbor doesn't re-render if objects do not inherit from BaseNode

### ISSUE THREAD

**Issue by haydenrou** [drborges/arbor#84]
Arbor should at least warn the user if they are attempting to store objects that do not inherit from `BaseNode`, because if they do not, Arbor will not be aware of their location in the tree and thus not re-render when expected. Additionally, a lot of the built in functionality being written into the docs will be unavailable.

**Comment by drborges** [comment]
This no longer applies since `ArborNode` has been removed in recent versions. With that said, currently Arbor by default will automatically:

1. Proxy any object literal, e.g.:
  ```ts
  const store = new Arbor({
    some: { application: "state" }
  })
  ```
3. Proxy any array literal, e.g.:
  ```ts
  const store = new Arbor([
    { some: { item: "1" } },
    { some: { item: "2" } },
  ])
  ```
4. Proxy any instance of `Map`, e.g.:
  ```ts
  const store = new Arbor(new Map<string, SomeType>())
  ```
5. Proxy any class decorated with the `@proxiable` decorator, e.g.:
  ```ts
  @proxiable
  class AppState {
    // some app state and business logic
  }

  const store = new Arbor(new AppState())
  ```
6. Proxy any class that defined a `ArborProxiable` Symbol prop, e.g.:
  ```ts
  class AppState {
    // some app state and business logic

   [ArborProxiable] = true
  }

  const store = new Arbor(new AppState())
  ```

For more details, there's more info on [this PR introducing](https://github.com/drborges/arbor/pull/94) this new decorator system.

The reason Arbor does not proxy any object it finds in the state is that it does not have control over third-party types and how they are built internally, for instance, Arbor is not able to handle classes that leverage `#private` fields simply because [JS Proxy cannot access #private fields](https://github.com/tc39/proposal-class-fields/issues/106), this is a recurrent problem on libraries using [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

At the moment there's no good way to warn users that the type they are using is missing the `@proxiable` decorator or the `ArborProxiable` prop because Arbor cannot make the distinction as to which props should or should not be proxiable.

I'd be curious to see how often people get into problems because they missed the decorator, if that becomes a trend, we can explore a slightly different idea, and make Arbor proxy every object by default, and the fields that should not be proxiable (for instance a `Date` field is an object...) then the user would mark them as `@unproxiable`... but I'm not sure if we'd be trading one problem for another at this point...
